#include<string>
#include<iostream>
#ifndef HEADER
#define HEADER
int test_static_var();
void check_vars();
void test_all_assignments();
void out_of_range_to_signed();
void int_to_unsigned();
void interesting_infinite_loop();
void exercise_2_3();
void initialize_wth_curly_braces();
void print_initial_values();
void exercise_2_9();
int find_consecutive();
void identifiers();
void exercise_2_14();
void compound_type_reference();
void ptr_initialization();
int book_details();
int book_more_program();
int test_using();
int namespace_exercise1();
std::string string_declaration();
void string_ops();
void string_read_multiple();
void string_read_lines();
void get_size();
void string_comparison();
void string_input_by_word();
void string_comparison_exercise();
void toUpperString();
void check_the_range_for_statement();
void get_punct_count();
void change_to_upper();
void first_word_to_upper();
void change_to_X();
void exercise_3_8();
void vector_intro();
void read_into_vector();
void manipulate_int_vector();
void grade_bucket();
void sum_elements();
void iterator_play();
void iterator_declarations();
void exerceise1();
void exercise2();
void exercise3();
void binary_search();
void array_exercise1();
#endif

